### ISSUE TITLE
error: no matching function for call to 'ItemAdd

### ISSUE THREAD

**Issue by Martinfx** [Jaysmito101/TerraForge3D#65]
**Describe the bug**
hi
i have issue with build on FreeBSD 14.1. I used default branch

```
/usr/home/maxfx/Documents/FreeBSD-Ports/terraforge3D/work/TerraForge3D-f36910e/TerraForge3D/src/Base/ImGuiCurveEditor.cpp:14:9: warning: 'IMGUI_DEFINE_MATH_OPERATORS' macro redefined [-Wmacro-redefined]
   14 | #define IMGUI_DEFINE_MATH_OPERATORS
      |         ^
<command line>:1:9: note: previous definition is here
    1 | #define IMGUI_DEFINE_MATH_OPERATORS 1
      |         ^
/usr/home/maxfx/Documents/FreeBSD-Ports/terraforge3D/work/TerraForge3D-f36910e/TerraForge3D/src/Base/ImGuiCurveEditor.cpp:608:7: error: no matching function for call to 'ItemAdd'
  608 |         if (!ItemAdd(bb, NULL))
      |              ^~~~~~~
/usr/home/maxfx/Documents/FreeBSD-Ports/terraforge3D/work/TerraForge3D-f36910e/./TerraForge3D/vendor/imgui/imgui_internal.h:3057:29: note: candidate function not viable: no known conversion from 'std::nullptr_t' to 'ImGuiID' (aka 'unsigned int') for 2nd argument
 3057 |     IMGUI_API bool          ItemAdd(const ImRect& bb, ImGuiID id, const ImRect* nav_bb = NULL, ImGuiItemFlags extra_flags = 0);
      |                             ^                         ~~~~~~~~~~
1 warning and 1 error generated.
ninja: build stopped: subcommand failed.

```

**To Reproduce**
1. git clone
2. cmake ..
3. gmake

**Desktop (please complete the following information):**
* FreeBSD hades 14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64
* FreeBSD clang version 18.1.5

**Comment by Martinfx** [comment]
I fixed this problem.
