### ISSUE TITLE
error: no member named 'GetKeyIndex' in namespace 'ImGui'

### ISSUE THREAD

**Issue by Martinfx** [Jaysmito101/TerraForge3D#64]
**Describe the bug**
hi
i have issue with build on FreeBSD 14.1. I used default branch

```

/home/maxfx/Documents/TerraForge3D/TerraForge3D/vendor/imgui-node-editor/imgui_node_editor.cpp:4394:80: error: no member named 'GetKeyIndex' in namespace 'ImGui'
 4394 |     if (io.KeyCtrl && !io.KeyShift && !io.KeyAlt && ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_X)))
      |                                                                         ~~~~~~~^
/home/maxfx/Documents/TerraForge3D/TerraForge3D/vendor/imgui-node-editor/imgui_node_editor.cpp:4396:80: error: no member named 'GetKeyIndex' in namespace 'ImGui'
 4396 |     if (io.KeyCtrl && !io.KeyShift && !io.KeyAlt && ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_C)))
      |                                                                         ~~~~~~~^
/home/maxfx/Documents/TerraForge3D/TerraForge3D/vendor/imgui-node-editor/imgui_node_editor.cpp:4398:80: error: no member named 'GetKeyIndex' in namespace 'ImGui'
 4398 |     if (io.KeyCtrl && !io.KeyShift && !io.KeyAlt && ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_V)))
      |                                                                         ~~~~~~~^
/home/maxfx/Documents/TerraForge3D/TerraForge3D/vendor/imgui-node-editor/imgui_node_editor.cpp:4402:81: error: no member named 'GetKeyIndex' in namespace 'ImGui'
 4402 |     if (!io.KeyCtrl && !io.KeyShift && !io.KeyAlt && ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_Space)))
      |                                                                          ~~~~~~~^
/home/maxfx/Documents/TerraForge3D/TerraForge3D/vendor/imgui-node-editor/imgui_node_editor.cpp:4956:68: error: no member named 'GetKeyIndex' in namespace 'ImGui'
 4956 |     if (Editor->CanAcceptUserInput() && ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_Delete)) && Editor->AreShortcutsEnabled())
      |                                                             ~~~~~~~^

```

**To Reproduce**
1. git clone
2. cmake ..
3. gmake

**Desktop (please complete the following information):**
* FreeBSD hades 14.1-RELEASE-p5 FreeBSD 14.1-RELEASE-p5 GENERIC amd64
* FreeBSD clang version 18.1.5

**Comment by Jaysmito101** [comment]
Looks like some mismatch in Imgui version, somehow its not getting the correct versions of the header

**Comment by Martinfx** [comment]
I fixed this problem.
